### ISSUE TITLE
Cannot create Teams on https://taskforce.sh/

### ISSUE THREAD

**Issue by Mulhem** [taskforcesh/issues#136] opened 2023-08-24 05:54 UTC
Creating teams is failing with 500

**Comment by manast** [comment] 2023-08-24 08:09
I cannot reproduce this. It could be that there is something specific to your subscription, could you please email me at manast@taskforce.sh with the email of the owner of the subscription?

**Comment by manast** [comment] 2024-11-03 19:55
Closing as this seems to be working properly.

**Closed as completed by manast** 2024-11-03 19:55 UTC
