### ISSUE TITLE
Which IP addresses to whitelist?

### ISSUE THREAD

**Issue by JVMartin** [taskforcesh/issues#38] opened 2020-06-02 19:36 UTC
Hi,

I'm trialing taskforce now.

I need to know which IP addresses to whitelist in order to allow your servers to connect to my Redis instances, without exposing my Redis instances to the rest of the internet unnecessarily.

Thanks,

-Jacob

**Comment by manast** [comment] 2020-06-02 21:00
Currently we do not have a NAT in our infrastructure so there is not a static IP you can whitelist, however if you use the taskforce connector you can achieve the same level of security since it will create a private websocket bridge between your redis instance and taskforce servers without needing to expose the redis instance to the world. The bridge is very lightweight so you can deploy it easily in the smallest instance you can get, you can use the provided Dockerfile for easy deploy.

**Comment by JVMartin** [comment] 2020-06-02 21:06
Thank you @manast , that makes sense. I'll set up an intermediate droplet with the taskforce connector installed as a proxy.

Feel free to close this issue, unless you want to use it as a reminder to eventually implement a static range of IPs.

**Comment by sbleon** [comment] 2020-07-22 15:27
We'd be more likely to use Taskforce.sh if it had static IPs that we could whitelist.

**Comment by sbleon** [comment] 2020-07-22 20:34
This is a duplicate of #4.

**Comment by manast** [comment] 2020-07-22 22:04
@sbleon thanks. I will try to up-prioritize this.

**Comment by manast** [comment] 2021-02-18 09:13
This has been recently added now: https://docs.taskforce.sh/getting-started/direct-redis-connection#securing-by-ip

**Closed as completed by manast** 2021-02-18 09:13 UTC
Labels: enhancement

**Comment by sbleon** [comment] 2021-02-18 15:19
Thanks, Manuel!

**Comment by JVMartin** [comment] 2021-02-18 17:21
@manast Because I was unable to use Taskforce without this feature, my free trial expired without me being able to try it out.

Can you please give me another trial? I'm Jacob Martin.

**Comment by manast** [comment] 2021-02-19 18:27
@JVMartin you should get a new trial if you login again, please let me know how it goes.

**Comment by JVMartin** [comment] 2021-02-24 22:52
@manast I'm in, thanks!! Will be trying it out this week.

**Comment by JVMartin** [comment] 2021-02-24 22:55
@manast I whitelisted `18.193.189.120` on my DigitalOcean managed Redis instance, then entered the host, port, password, and checked SSL, and it's giving this error in the UI:

![image](https://user-images.githubusercontent.com/4450814/109077024-61ad4880-76b0-11eb-869e-a5bdba4c58e9.png)

**Comment by JVMartin** [comment] 2021-02-24 23:01
I can access the Redis instance from anywhere except TaskForce.

Here's a screenshot of the DO setup (sensitive details redacted):
![image](https://user-images.githubusercontent.com/4450814/109077484-13e51000-76b1-11eb-9461-7fe641136cac.png)

**Comment by manast** [comment] 2021-02-25 09:46
Could you double check the host and port? I am testing with the same setup and is working:
![image](https://user-images.githubusercontent.com/95200/109134551-704e3b00-7756-11eb-9fde-eafff1b8b32d.png)
Did you activate TLS ?
![image](https://user-images.githubusercontent.com/95200/109134685-970c7180-7756-11eb-9543-1ee38b332551.png)

Btw, you will need to open the connection and save it again in order to trigger a reconnection in Taskforce
