### ISSUE TITLE
Dashboard gets stretched when selecting jobs, workers tabs

### ISSUE THREAD

**Issue by imagolive** [taskforcesh/issues#25] opened 2019-09-05 05:53 UTC
This is using firefox.

![stretched page](https://user-images.githubusercontent.com/23182810/64315375-6ece0780-cfe4-11e9-88a9-ae4e2d7460fe.png)

**Comment by imagolive** [comment] 2019-09-05 05:53
You have to scroll sideways to see stuff.

**Comment by manast** [comment] 2019-09-05 07:23
yes, it is a duplicate of this one: https://github.com/taskforcesh/issues/issues/19 
Will give it high prio.

**Comment by manast** [comment] 2019-09-08 15:50
Fixed!

**Closed as completed by manast** 2019-09-08 15:50 UTC
Labels: duplicate
